namespace :cache do
  namespace :clear do
    desc "Clear all caches"
    task :all => [:javascripts, :stylesheets]

    desc "Clear javascript caches"
    task :javascripts do
      FileUtils.rm_f Dir['public/javascripts/cache/[^.]*.js'] 
      FileUtils.rm_f 'public/javascripts/named_routes.js'
    end

    desc "Clear cached stylesheets (generated by ncss etc)"
    task :stylesheets do
      Dir['app/views/stylesheets/[^.]*.ncss'].each do |ncss|
        css = File.basename(ncss).sub(/ncss$/,'css')
        css = %Q[public/stylesheets/#{css}]
        FileUtils.rm_f(css) 
      end
      FileUtils.rm_f 'public/stylesheets/permissions.css'
    end
  end
end
