development:
  video_feed_url: 'http://example.com/video/feeds'
  video_base_url: 'http://example.com/videos'
  content_types:
    - Document
    - Folder
    - Image

test:
  video_feed_url: 'http://example.com/video/feeds'
  video_base_url: 'http://example.com/videos'
  content_types:
    - Document
    - Folder
    - Image

production:
  video_feed_url: 'http://example.com/video/feeds'
  video_base_url: 'http://example.com/videos'
  http_auth:
    name: tirade
    password: secret
  content_types:
    - Document
    - Folder
    - Image
